name: Build Image & Push to GHCR
on:   
  push:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-ghcr:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:

      - run: echo "IMAGE_NAME=$(echo '${{ github.repository}}' | tr '[:upper:]' '[:lower:]' )" >> $GITHUB_ENV
        shell: bash

      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
